# Generated by Django 2.2.3 on 2019-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appmodel',
            fields=[
                ('appno', models.IntegerField(primary_key=True, serialize=False)),
                ('floorno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('cost_p_sqyard', models.IntegerField()),
                ('total_sqyard', models.IntegerField()),
                ('other_exp', models.IntegerField()),
                ('facing', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=10)),
                ('total_cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('E_name', models.CharField(max_length=30)),
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('E_email', models.EmailField(max_length=254)),
                ('E_location', models.CharField(max_length=20)),
                ('E_doj', models.DateField()),
                ('E_remark', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plotmodel',
            fields=[
                ('plotno', models.IntegerField(primary_key=True, serialize=False)),
                ('roadno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('cost_p_sqyard', models.IntegerField()),
                ('total_sqyard', models.IntegerField()),
                ('other_exp', models.IntegerField()),
                ('facing', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=10)),
                ('total_cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
